language: java

jdk:
  - openjdk11
  - openjdk8

branches:
  only:
    - master
before_install:
  - 'chmod +x gradlew'
  - './gradlew --version'
install:
  - './gradlew assemble'
script: ./gradlew build -x test